[package]
name = "runners-initiative-manager"
version = "1.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.1.1", features = [] }

[dependencies]
tauri = { version = "2.4.1", features = [] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
rusqlite = { version = "0.32.0", features = ["bundled"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.25.0"
ts-rs = "10.1.0"
tauri-plugin-shell = "2.2.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
