// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Combatten { id: number, name: string, combatten_type: string, campaign_id: number, }