// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Combatten } from "./Combatten";

export interface Encounter { id: number, name: string, campaign_id: number, combattens: Array<Combatten>, }